### ISSUE TITLE
FlashStart: Bypass IP ranges

### ISSUE THREAD

**Issue by andre8244** [nethesis/dev#5976] opened 2021-03-18 16:55 UTC
Currently only IP addresses and CIDR subnets can bypass FlashStart filter.
Let's support bypass for IP ranges too.

**Proposed solution**

Allow the user to enter an IP range as **Bypass source** in **FlashStart > Settings** page

**Comment by gsanchietti** [comment] 2021-03-19 10:00
Current template implementation supports firewall objects while the UI doesn't support it.
An IP range can't be added to the UI because the firewall library supports only IP and CIDR as raw addresses.
Even if unlikely, some machine could have objects configured and the proposed change will cause regressions.

As improvement, we could support firewall objects inside the UI, but this is a different feature request.

Closing as **wontfix**.

**Closed as completed by gsanchietti** 2021-03-19 10:00 UTC
Labels: invalid
