### ISSUE TITLE
NethVoice 14: wizard create migration management section

### ISSUE THREAD

**Issue by SebastianMB-IT** [nethesis/dev#5447] opened 2018-08-21 08:59 UTC
Create Wizard front-end for Nethvoice old version migration:

**See also**

- https://github.com/nethesis/nethvoice-upgrade-manager
- https://github.com/nethesis/nethvoice-wizard-test

**Comment by SebastianMB-IT** [comment] 2018-12-05 14:48
**Last version**
- http://packages.nethesis.it/nethserver/enterprise/7.5.1804/nethesis-autobuild/x86_64/Packages/nethvoice-wizard-ui-14.1.6-1.17.pr46.g15e378b.ns7.noarch.rpm

**Comment by Stell0** [comment] 2018-12-07 16:32
duplicate of https://github.com/nethesis/dev/issues/5454

**Closed by Stell0** 2018-12-07 16:32 UTC
Labels: feature
